const BANCO_QUESTOES = {
    algebra_expressoes: {
        dificil: [
            { q: "Uma esfera condutora metálica com carga Q é colocada em contato com uma segunda esfera idêntica e neutra, sendo separadas em seguida. Qual a expressão para a carga final da primeira esfera?", res: "Q/2" },
            { q: "Uma esfera condutora A, com carga Q, toca sucessivamente em duas outras esferas idênticas e neutras (primeiro em B, depois em C). Qual a carga final da esfera A?", res: "Q/4" },
            { q: "Uma esfera idêntica A com carga 4Q toca em uma esfera B neutra. Em seguida, a esfera B toca em uma esfera C neutra. Qual a carga final da esfera B?", res: "Q" },
            { q: "Três esferas condutoras idênticas (A, B e C) possuem cargas iniciais 8Q, -2Q e 0, respectivamente. A esfera A toca em B, e logo após, A toca em C. Qual a carga final da esfera C?", res: "1.5Q" },
            { q: "Duas esferas idênticas possuem cargas iniciais 3Q e Q. Elas são colocadas em contato e depois separadas. Qual a carga final de cada uma?", res: "2Q" },
            { q: "Quatro esferas metálicas idênticas (A, B, C e D) estão neutras, exceto A, que possui carga Q. A esfera A toca B, depois C, e depois D, sucessivamente. Qual a carga final da esfera A?", res: "Q/8" },
            { q: "Duas esferas idênticas, A com carga 5Q e B com carga -5Q, são colocadas em contato. Qual a carga final da esfera A?", res: "0" },
            { q: "Uma esfera A de carga Q toca uma esfera idêntica B de carga 3Q. Após separadas, a esfera B toca uma esfera C neutra. Qual a carga final da esfera C?", res: "2Q" },
            { q: "Um veículo viaja a primeira metade do percurso com velocidade constante 'v' e a segunda metade com velocidade '2v'. Qual a expressão da velocidade média de todo o percurso?", res: "4v/3" },
            { q: "Um carro viaja metade do tempo de sua viagem com velocidade 'v' e a outra metade do tempo com velocidade '3v'. Qual a expressão da velocidade média?", res: "2v" },
            { q: "Um corpo percorre uma distância 'd' em um tempo 't'. Se a velocidade média for duplicada, qual a expressão para o novo tempo de viagem?", res: "t/2" },
            { q: "Um bloco de massa 'm' é acelerado de repouso até uma velocidade '2v' em um tempo 't'. Qual a expressão para a força resultante média aplicada (use F = m*a)?", res: "2mv/t" },
            { q: "A energia cinética de um corpo é expressa por (m*v^2)/2. Qual será a nova energia cinética se a velocidade do corpo triplicar?", res: "9mv^2/2" },
            { q: "Um gás ideal sofre uma compressão onde seu volume 'V' cai pela metade e sua temperatura absoluta 'T' dobra. Pela lei dos gases perfeitos, qual a expressão da nova pressão em relação à pressão inicial 'P'?", res: "4P" },
            { q: "A densidade de um fluido é a massa 'm' dividida pelo volume 'V'. Se misturarmos duas amostras deste mesmo fluido, dobrando a massa e reduzindo o volume à metade, qual a nova densidade?", res: "4m/V" },
            { q: "Um retângulo tem sua base expressa por 'x+3' e sua altura por 'x-3'. Qual a expressão simplificada da sua área?", res: "x^2-9" },
            { q: "O lado de um quadrado mede 'x/2'. Qual a expressão que representa o perímetro desse quadrado?", res: "2x" },
            { q: "Um cubo possui arestas de medida '3x'. Qual a expressão algébrica para o seu volume?", res: "27x^3" },
            { q: "A base de um triângulo mede '4x' e sua altura mede 'x/2'. Qual a área deste triângulo?", res: "x^2" },
            { q: "Um terreno retangular tem comprimento equivalente ao dobro da sua largura 'L'. Se o proprietário quiser cercar todo o terreno, qual será a expressão do perímetro?", res: "6L" },
            { q: "Um fio de arame de comprimento 'C' é dobrado para formar um quadrado perfeito. Qual a expressão da área desse quadrado?", res: "C^2/16" },
            { q: "Um trapézio possui base maior medindo '2x', base menor medindo 'x' e altura medindo '4'. Qual a expressão da sua área?", res: "6x" },
            { q: "A diagonal de um quadrado de lado 'L' é dada por L√2. Qual a expressão da diagonal de um quadrado cuja área é '16x^2'?", res: "4x√2" },
            { q: "Um triângulo retângulo possui catetos medindo '3x' e '4x'. Qual a expressão para a medida da hipotenusa?", res: "5x" },
            { q: "A área de um círculo é π*R^2. Se o diâmetro de um círculo for '4x', qual a expressão da sua área?", res: "4πx^2" },
            { q: "Uma caixa sem tampa possui formato de paralelepípedo com base quadrada de lado 'x' e altura '2x'. Qual a expressão para a área total de material necessário para fabricá-la?", res: "9x^2" },
            { q: "Um produto custava 'P' reais. Ele sofreu um aumento de 20% e, no mês seguinte, um desconto de 20%. Qual a expressão matemática para o novo preço do produto?", res: "0.96P" },
            { q: "Uma herança de valor 'H' será dividida entre três irmãos. O mais velho receberá o dobro do irmão do meio, e o caçula receberá a mesma quantia que o irmão do meio. Qual a expressão para o valor recebido pelo caçula?", res: "H/4" },
            { q: "O custo de produção de uma fábrica envolve um valor fixo de R$ 500,00 mais R$ 3,00 por peça 'p' produzida. Qual a expressão matemática que representa o custo médio (por unidade) de produção?", res: "(500+3p)/p" },
            { q: "Um capital 'C' é investido a juros simples com uma taxa de 5% ao mês durante 't' meses. Qual a expressão do montante (capital + juros) ao final do período?", res: "C(1+0.05t)" },
            { q: "Uma loja vende 'x' unidades de um produto a um preço 'p' cada. O custo fixo mensal da loja é 'C'. Qual a expressão matemática para o lucro líquido dessa loja?", res: "px-C" },
            { q: "Uma conta de restaurante de valor 'V' será dividida igualmente entre 'N' amigos. Se eles decidirem incluir 10% de gorjeta para o garçom, qual a expressão do valor que cada amigo deverá pagar?", res: "1.1V/N" },
            { q: "Um motorista de aplicativo ganha R$ 5,00 por corrida mais R$ 1,50 por quilômetro rodado 'k'. Se o aplicativo retém 20% do valor total arrecadado, qual a expressão do lucro do motorista em uma corrida?", res: "0.8(5+1.5k)" },
            { q: "Um tanque possui duas torneiras. A primeira enche o tanque em 'x' horas. A segunda enche o mesmo tanque em 'y' horas. Se ambas forem abertas simultaneamente, qual a expressão para o tempo total de enchimento?", res: "xy/(x+y)" },
            { q: "Uma ação na bolsa de valores abriu valendo 'A'. No primeiro dia, caiu 50%. No segundo dia, subiu 50% em relação ao fechamento do dia anterior. Qual a expressão que representa o valor atual da ação?", res: "0.75A" },
            { q: "Um trabalhador poupa mensalmente a terça parte do seu salário 'S'. Dessa poupança, ele destina a quarta parte para investir em ações. Qual a fração do salário total que ele investe em ações?", res: "S/12" },
            { q: "O salário de um funcionário 'S' teve um reajuste e passou a ser '1.25S'. Isso equivale a um aumento de quantos por cento?", res: "25" },
            { q: "Uma empresa tem uma receita 'R' e despesas que equivalem a 60% dessa receita. Sobre o lucro (o que sobra), é cobrado um imposto de 25%. Qual a expressão matemática para o lucro após os impostos?", res: "0.3R" },
            { q: "A população de bactérias 'B' de uma cultura triplica a cada dia. Qual a expressão da população após 3 dias inteiros passados?", res: "27B" },
            { q: "João tem o triplo da idade que Maria 'm' tinha há 5 anos. Qual a expressão matemática para a idade atual de João?", res: "3(m-5)" }
        ]
    }
};
